create extension if not exists pgcrypto;

create table if not exists public.dental_clinics (
  clinic_id text primary key,
  clinic_name text not null,
  timezone text not null default 'Asia/Kolkata',
  address text,
  phone text,
  whatsapp text,
  slot_interval_minutes integer not null default 30,
  human_handoff_contact text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dental_dentists (
  dentist_id text primary key,
  clinic_id text not null references public.dental_clinics(clinic_id) on delete cascade,
  dentist_name text not null,
  specialty text,
  google_calendar_id text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.dental_services (
  service_id text primary key,
  clinic_id text not null references public.dental_clinics(clinic_id) on delete cascade,
  service_name text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  buffer_minutes integer not null default 0 check (buffer_minutes >= 0),
  price_inr integer,
  active boolean not null default true
);

create table if not exists public.dental_dentist_services (
  dentist_id text not null references public.dental_dentists(dentist_id) on delete cascade,
  service_id text not null references public.dental_services(service_id) on delete cascade,
  primary key (dentist_id, service_id)
);

create table if not exists public.dental_schedules (
  id bigint generated by default as identity primary key,
  dentist_id text not null references public.dental_dentists(dentist_id) on delete cascade,
  weekday integer not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  active boolean not null default true,
  check (end_time > start_time)
);

create table if not exists public.dental_closures (
  id uuid primary key default gen_random_uuid(),
  clinic_id text not null references public.dental_clinics(clinic_id) on delete cascade,
  dentist_id text references public.dental_dentists(dentist_id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text,
  check (ends_at > starts_at)
);

create table if not exists public.dental_appointments (
  appointment_id uuid primary key default gen_random_uuid(),
  clinic_id text not null references public.dental_clinics(clinic_id) on delete cascade,
  dentist_id text not null references public.dental_dentists(dentist_id),
  service_id text not null references public.dental_services(service_id),
  patient_name text not null,
  patient_phone text not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  status text not null default 'CONFIRMED'
    check (status in ('HELD','CONFIRMED','RESCHEDULED','CANCELLED','COMPLETED','NO_SHOW','HUMAN_HANDOFF')),
  google_calendar_event_id text,
  source text not null default 'voice_ai',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_time > start_time)
);

create table if not exists public.dental_handoffs (
  id uuid primary key default gen_random_uuid(),
  clinic_id text not null references public.dental_clinics(clinic_id) on delete cascade,
  patient_phone text,
  patient_name text,
  reason text not null,
  status text not null default 'OPEN'
    check (status in ('OPEN','ACCEPTED','RESOLVED')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.dental_message_log (
  id uuid primary key default gen_random_uuid(),
  clinic_id text not null references public.dental_clinics(clinic_id) on delete cascade,
  patient_phone text,
  channel text not null,
  direction text not null check (direction in ('INBOUND','OUTBOUND')),
  message_type text,
  body text,
  created_at timestamptz not null default now()
);

create index if not exists dental_appointments_dentist_time_idx
  on public.dental_appointments(dentist_id, start_time, end_time);

create index if not exists dental_appointments_patient_idx
  on public.dental_appointments(patient_phone, start_time desc);

create index if not exists dental_closures_time_idx
  on public.dental_closures(clinic_id, starts_at, ends_at);

create index if not exists dental_handoffs_status_idx
  on public.dental_handoffs(status, created_at);

-- Demo seed data
insert into public.dental_clinics
  (clinic_id, clinic_name, timezone, address, phone, whatsapp, slot_interval_minutes, human_handoff_contact)
values
  ('brightsmile-demo', 'BrightSmile Dental Clinic', 'Asia/Kolkata',
   'Sector 22, Chandigarh, India', '+91-170-555-0101', '+91-99990-00001', 30, 'clinic-reception')
on conflict (clinic_id) do nothing;

insert into public.dental_dentists
  (dentist_id, clinic_id, dentist_name, specialty, google_calendar_id)
values
  ('dr-aditi', 'brightsmile-demo', 'Dr. Aditi Mehta', 'General Dentistry', 'replace-with-google-calendar-id'),
  ('dr-rohan', 'brightsmile-demo', 'Dr. Rohan Kapoor', 'Endodontics', 'replace-with-google-calendar-id'),
  ('dr-neha', 'brightsmile-demo', 'Dr. Neha Verma', 'Orthodontics', 'replace-with-google-calendar-id')
on conflict (dentist_id) do nothing;

insert into public.dental_services
  (service_id, clinic_id, service_name, duration_minutes, buffer_minutes, price_inr)
values
  ('consultation', 'brightsmile-demo', 'Dental Consultation', 20, 10, 500),
  ('cleaning', 'brightsmile-demo', 'Dental Cleaning', 30, 10, 1500),
  ('filling', 'brightsmile-demo', 'Dental Filling', 45, 10, 2000),
  ('root-canal', 'brightsmile-demo', 'Root Canal Appointment', 60, 10, null),
  ('ortho-consult', 'brightsmile-demo', 'Orthodontic Consultation', 30, 10, 800)
on conflict (service_id) do nothing;

insert into public.dental_dentist_services (dentist_id, service_id)
values
  ('dr-aditi','consultation'),
  ('dr-aditi','cleaning'),
  ('dr-aditi','filling'),
  ('dr-rohan','consultation'),
  ('dr-rohan','root-canal'),
  ('dr-neha','consultation'),
  ('dr-neha','ortho-consult')
on conflict do nothing;

-- PostgreSQL weekday convention used by this demo: Sunday=0 ... Saturday=6
insert into public.dental_schedules (dentist_id, weekday, start_time, end_time)
select dentist_id, weekday, start_time::time, end_time::time
from (values
  ('dr-aditi',1,'09:00','13:00'),('dr-aditi',1,'14:00','18:00'),
  ('dr-aditi',2,'09:00','13:00'),('dr-aditi',2,'14:00','18:00'),
  ('dr-aditi',3,'09:00','13:00'),('dr-aditi',3,'14:00','18:00'),
  ('dr-aditi',4,'09:00','13:00'),('dr-aditi',4,'14:00','18:00'),
  ('dr-aditi',5,'09:00','13:00'),('dr-aditi',5,'14:00','18:00'),
  ('dr-aditi',6,'09:00','14:00'),
  ('dr-rohan',1,'10:00','13:00'),('dr-rohan',1,'14:00','18:00'),
  ('dr-rohan',3,'10:00','13:00'),('dr-rohan',3,'14:00','18:00'),
  ('dr-rohan',5,'10:00','13:00'),('dr-rohan',5,'14:00','18:00'),
  ('dr-neha',2,'09:00','13:00'),('dr-neha',2,'14:00','18:00'),
  ('dr-neha',4,'09:00','13:00'),('dr-neha',4,'14:00','18:00'),
  ('dr-neha',6,'09:00','14:00')
) as s(dentist_id, weekday, start_time, end_time)
where not exists (
  select 1 from public.dental_schedules d
  where d.dentist_id=s.dentist_id
    and d.weekday=s.weekday
    and d.start_time=s.start_time::time
    and d.end_time=s.end_time::time
);
